import {generateLevel,GameState,validateLevel} from "./game.js";import {getLang,applyLang,t,t as tr} from "./i18n.js";import {SoundPlayer,Haptics} from "./audio.js";
const settings={sound:localStorage.getItem("soundEnabled")!=="false",haptics:localStorage.getItem("hapticsEnabled")!=="false"};const sound=new SoundPlayer(settings),haptics=new Haptics(settings);let lang=applyLang(getLang()),levelNo=Number(localStorage.getItem("arrowLevel")||1),seed=Number(localStorage.getItem("arrowSeed")||1337),level=generateLevel(levelNo,seed),state=new GameState(level),selectedHint=null;
const canvas=document.querySelector("#board"),ctx=canvas.getContext("2d"),score=document.querySelector("#score"),hint=document.querySelector("#hint");
function resize(){const r=document.querySelector("#board-wrap").getBoundingClientRect(),size=Math.min(r.width-8,r.height-20,560);canvas.width=canvas.height=Math.max(280,size);draw()}function cell(){return canvas.width/Math.max(level.w,level.h)}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);const s=cell();ctx.fillStyle="rgba(19,27,83,.3)";ctx.fillRect(8,8,s*level.w-16,s*level.h-16);for(const p of level.pieces){if(state.removed.has(p.id))continue;const glow=p.id===selectedHint;for(const [x,y] of p.cells){const px=x*s,py=y*s;ctx.save();ctx.translate(px+s/2,py+s/2);ctx.rotate(p.dir.angle);ctx.fillStyle=glow?"#ffd85e":["#ff7180","#65d58b","#6bb8ff","#c78cff","#ffae62"][p.id%5];ctx.shadowColor=glow?"#fff":"rgba(0,0,0,.25)";ctx.shadowBlur=glow?14:5;ctx.beginPath();ctx.roundRect(-s*.34,-s*.34,s*.68,s*.68,12);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="rgba(255,255,255,.22)";ctx.beginPath();ctx.moveTo(-s*.28,-s*.22);ctx.lineTo(s*.2,-s*.22);ctx.lineTo(s*.3,-s*.08);ctx.lineTo(-s*.18,-s*.08);ctx.closePath();ctx.fill();ctx.restore()}}score.textContent=`${state.removed.size} / ${level.pieces.length}`;document.querySelector("#level-label").textContent=levelNo}
function pieceAt(x,y){const s=cell(),gx=Math.floor(x/s),gy=Math.floor(y/s);return level.pieces.find(p=>!state.removed.has(p.id)&&p.cells.some(([a,b])=>a===gx&&b===gy))}
function tap(e){sound.unlock();const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)*canvas.width/r.width,y=(e.clientY-r.top)*canvas.height/r.height,p=pieceAt(x,y);if(!p)return;if(state.move(p.id)){sound.play("tap");haptics.tap();selectedHint=null;draw();if(state.won()){sound.play("win");document.querySelector("#win-copy").textContent=tr("cleared",lang);document.querySelector("#win-overlay").hidden=false}}else{sound.play("blocked");haptics.blocked();hint.textContent=tr("blocked",lang);hint.classList.add("show");setTimeout(()=>hint.classList.remove("show"),1300)}}
canvas.addEventListener("pointerdown",tap);canvas.addEventListener("keydown",e=>{if(!["Enter"," "].includes(e.key))return;e.preventDefault();const p=level.pieces.find(x=>x.id===selectedHint)||level.pieces.find(x=>!state.removed.has(x.id));if(p)tap({clientX:canvas.getBoundingClientRect().left+(p.x+.5)*cell(),clientY:canvas.getBoundingClientRect().top+(p.y+.5)*cell()})});window.addEventListener("resize",resize);
function reload(n=levelNo){levelNo=n;level=generateLevel(levelNo,seed);state=new GameState(level);localStorage.setItem("arrowLevel",levelNo);selectedHint=null;document.querySelector("#win-overlay").hidden=true;resize()}
document.querySelector("#undo-button").onclick=()=>{if(state.undo()){sound.play("tap");draw()}};document.querySelector("#reset-button").onclick=()=>{state.reset();draw()};document.querySelector("#hint-button").onclick=()=>{selectedHint=level.order.find(id=>!state.removed.has(id));hint.textContent=tr("hintText",lang);hint.classList.add("show");draw();setTimeout(()=>{hint.classList.remove("show");selectedHint=null;draw()},1500)};document.querySelector("#next-button").onclick=()=>reload(levelNo+1);document.querySelector("#replay-button").onclick=()=>reload(levelNo);
const settingsOverlay=document.querySelector("#settings-overlay");document.querySelector("#settings-button").onclick=()=>{sound.play("tap");settingsOverlay.hidden=false};document.querySelector("#close-settings").onclick=()=>settingsOverlay.hidden=true;document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>settingsOverlay.hidden=true);
function toggle(id,key){const b=document.querySelector(id);b.classList.toggle("on",settings[key]);b.onclick=()=>{settings[key]=!settings[key];localStorage.setItem(key==="sound"?"soundEnabled":"hapticsEnabled",String(settings[key]));b.classList.toggle("on",settings[key])}}toggle("#sound-toggle","sound");toggle("#haptics-toggle","haptics");document.querySelector("#reset-best").onclick=()=>{localStorage.removeItem("arrowLevel");reload(1)};
const hub=new URLSearchParams(location.search).get("hub")||"https://mpmisha.github.io/playground/";const hubOrigin=new URL(hub).origin;const back=document.querySelector("#back-games");if(new URLSearchParams(location.search).has("hub")){back.hidden=false;back.onclick=()=>window.parent!==window?window.parent.postMessage({type:"playground:back"},hubOrigin):location.href=hub}window.addEventListener("message",e=>{if(e.origin!==hubOrigin||e.data?.type!=="playground:lang")return;lang=applyLang(e.data.lang);draw()});
if(!validateLevel(level))reload(levelNo);if("serviceWorker"in navigator)navigator.serviceWorker.register("./service-worker.js");resize();
